package jp.co.asnew

import jp.co.asnew.chunk.*
import jp.co.asnew.entity.*

rule "sub 3 rule"
//	salience 100
	activation-group "RuleB"
	no-loop false
	lock-on-active true
	agenda-group "agendaSub1"
//	auto-focus true
	when
		$report : Report( volume == 3 || volume == 1 )
		$unitCost : UnitCost()
	then
		modify($unitCost) { setVolume($report.getVolume()), setCost(2 * $report.getVolume()) };
	end
