package jp.co.asnew

import jp.co.asnew.chunk.*
import jp.co.asnew.entity.*

rule "common Sub Rules 2"
	// rule attributes
	activation-group "CommonSubRulesA"
	no-loop false
	lock-on-active true
	agenda-group "CommonSubRulesA"
	// rule
	when
		$report: Report(volume == 2 || volume == 1)
		$unitCost: UnitCost()
	then
		modify($unitCost) {
			setVolume($report.getVolume()),
			setCost(200 * $report.getVolume())
		};
end
