package jp.co.asnew

import jp.co.asnew.chunk.*
import jp.co.asnew.entity.*

rule "1 rule"
//	salience 1
	activation-group "RuleA"
	no-loop false
	lock-on-active true
	agenda-group "agendaA"
	when
		$report : Report( volume == 1 )
		$unitCost : UnitCost()
	then
		modify($unitCost) { setVolume($report.getVolume()), setCost(10 * $report.getVolume()) };
	end

rule "2 rule"
//	salience 50
	activation-group "RuleA"
	no-loop false
	lock-on-active true
	agenda-group "agendaA"
	when
		$report : Report( volume == 2 || volume == 1)
		$unitCost : UnitCost()
	then
		modify($unitCost) { setVolume($report.getVolume()), setCost(100 * $report.getVolume()) };
	end

rule "3 rule"
//	salience 100
	activation-group "RuleA"
	no-loop false
	lock-on-active true
	agenda-group "agendaB"
//	auto-focus true
	when
		$report : Report( volume == 3 || volume == 1 )
		$unitCost : UnitCost()
	then
		modify($unitCost) { setVolume($report.getVolume()), setCost($report.getVolume()) };
	end
